# -*- coding: utf-8 -*-
# Generated by Django 1.10.9 on 2018-10-16 06:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import general.fields
import general.functions
import geoposition.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(unique=True)),
                ('company_name', models.CharField(max_length=255)),
                ('main_email', models.EmailField(max_length=254)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DistanceErrorLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, max_length=500, null=True, upload_to=general.functions.path_and_rename)),
                ('address', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('profile', models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='userprofile.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeWorkDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', general.fields.IntegerRangeField(choices=[('', 'Choose Hours'), (60, '1 Hours'), (120, '2 Hours'), (180, '3 Hours'), (240, '4 Hours'), (300, '5 Hours'), (360, '6 Hours'), (420, '7 Hours'), (480, '8 Hours')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ExcelDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excelfile', models.FileField(upload_to='documents/excel')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('our_company', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('minute', general.fields.IntegerRangeField()),
                ('work_times', general.fields.IntegerRangeField(default=1)),
                ('image', models.ImageField(blank=True, max_length=500, null=True, upload_to=general.functions.path_and_rename)),
                ('address', models.TextField()),
                ('position', geoposition.fields.GeopositionField(max_length=42)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-our_company', '-date'],
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
            },
        ),
        migrations.CreateModel(
            name='LocationDistance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_company', models.BooleanField(default=False)),
                ('minute', models.IntegerField()),
                ('distance', models.DecimalField(decimal_places=2, max_digits=19)),
                ('location1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='content.Location')),
                ('location2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='content.Location')),
            ],
        ),
        migrations.CreateModel(
            name='LocationOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_index', general.fields.IntegerRangeField()),
                ('main_process', models.BooleanField(default=False)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Location')),
            ],
        ),
        migrations.CreateModel(
            name='PlanEmployeeWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', general.fields.IntegerRangeField()),
                ('minute', general.fields.IntegerRangeField(default=0)),
                ('difference_minute', general.fields.IntegerRangeField(default=0)),
                ('is_empty', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlanLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complated', models.BooleanField(default=False)),
                ('rejcected', models.BooleanField(default=False)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('main_plan', models.BooleanField(default=False)),
                ('sub_plan', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', general.fields.IntegerRangeField(choices=[(1, 'mandag'), (2, 'tirsdag'), (3, 'onsdag'), (4, 'torsdag'), (5, 'fredag'), (6, 'lørdag'), (7, 'søndag')], unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='planemployeework',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.WorkDay'),
        ),
        migrations.AddField(
            model_name='planemployeework',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Employee'),
        ),
        migrations.AddField(
            model_name='locationorder',
            name='plan_employee_work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.PlanEmployeeWork'),
        ),
        migrations.AddField(
            model_name='employeeworkday',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.WorkDay'),
        ),
        migrations.AddField(
            model_name='employeeworkday',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Employee'),
        ),
        migrations.AddField(
            model_name='distanceerrorlog',
            name='location1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='content.Location'),
        ),
        migrations.AddField(
            model_name='distanceerrorlog',
            name='location2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='content.Location'),
        ),
        migrations.AlterUniqueTogether(
            name='planemployeework',
            unique_together=set([('employee', 'week', 'day')]),
        ),
        migrations.AlterUniqueTogether(
            name='employeeworkday',
            unique_together=set([('employee', 'day')]),
        ),
    ]
