# -*- coding: utf-8 -*-
# Generated by Django 1.10.9 on 2018-10-24 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planemployeework',
            name='is_full',
            field=models.BooleanField(default=False),
        ),
    ]
