# -*- coding: utf-8 -*-
# Generated by Django 1.10.9 on 2018-11-13 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_planemployeework_is_full'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinformation',
            name='task_status_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
