# -*- coding: utf-8 -*-
# Generated by Django 1.10.9 on 2018-10-16 06:33
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, max_length=500, null=True, upload_to='profile_photos')),
                ('type', models.CharField(choices=[('admin-person', 'Admin'), ('employee-person', 'Employee')], default='employee-person', max_length=100)),
                ('address', models.TextField(blank=True, null=True)),
                ('activation_key', models.CharField(blank=True, editable=False, max_length=40)),
                ('reset_token_key', models.CharField(blank=True, editable=False, max_length=40)),
                ('key_expires', models.DateTimeField(blank=True, default=datetime.datetime(2018, 10, 16, 6, 33, 33, 838309, tzinfo=utc), editable=False, null=True)),
                ('reset_key_expires', models.DateTimeField(blank=True, default=datetime.datetime(2018, 10, 16, 6, 33, 33, 838354, tzinfo=utc), editable=False, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
