# -*- coding: utf-8 -*-
# Generated by Django 1.10.9 on 2018-10-24 13:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='key_expires',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 10, 24, 13, 36, 31, 914937, tzinfo=utc), editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='reset_key_expires',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 10, 24, 13, 36, 31, 914981, tzinfo=utc), editable=False, null=True),
        ),
    ]
