# -*- coding: utf-8 -*-
# Generated by Django 1.10.9 on 2018-11-13 10:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_auto_20181108_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='key_expires',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 11, 13, 10, 37, 25, 327928, tzinfo=utc), editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='reset_key_expires',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 11, 13, 10, 37, 25, 327970, tzinfo=utc), editable=False, null=True),
        ),
    ]
